services:
  - type: web
    name: ai-resume-screening
    env: python
    plan: free
    buildCommand: ""
    startCommand: streamlit run app.py --server.port=$PORT --server.enableCORS false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
